### ISSUE TITLE
Not working with zdaemon? 

### ISSUE THREAD

**Issue by sdwvit** [j-palomo/JPHUD#3]
Hey,

your mod seems like what i was looking for, though I couldn't make it work with Zdaemon
Could you post instruction how to make it work with this port?

**Comment by j-palomo** [comment]
Support for ZDoom was dropped. As far as I know, Zdaemon is based on a (very) old version of ZDoom. Even my earliest builds don't work on the current version of Zdaemon. No support for Zdaemon is planned.
